# -- coding: utf-8 --

msfs_mode = 1
icao = "loww"

@AlternativeStopPositions
def customOffset_vienna(aircraftData):
    table = {
        0: 1.00,
		221: 5.10,
		223: 5.10,
		300: 5.10,
		318: 5.10,
		319: 5.10,
		320: 5.10,
		321: 5.10,
		330: 9.00,
		340: 9.00,
		350: 9.00,
		707: 5.10,
		717: 5.10,
		727: 5.10,
		737: 5.10,
		747: 9.10,
		757: 9.10,
		200: 5.10,
		300: 5.10,
		1000: 5.10,
		146: 5.10,
		140: 5.10,
		145: 5.10,
		170: 5.10,
		175: 5.10,
		195: 5.10,
		42: 5.10,
		72: 5.10,
		380: 8.10,
		11: 5.10,
    }

    table787 = {
        0: 5.00,
        8: 5.00,
        9: 5.00,
        10: 5.00,
    }

    table777 = {
        0: 5.00,
        200: 5.00,
        300: 5.00,
    }

    if aircraftData.idMajor == 777:
        return Distance.fromMeters(table777.get(aircraftData.idMinor, 0.00))
    elif aircraftData.idMajor == 787:
        return Distance.fromMeters(table787.get(aircraftData.idMinor, 0.00))
    else:
            return Distance.fromMeters(table.get(aircraftData.idMajor, 0))

parkings = {
	GATE_A : {
		None : (),
			30 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			31 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			32 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			33 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			34 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			35 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			36 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			41 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			42 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			43 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			44 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			45 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			45 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			46 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			47 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			48 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			49 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			51 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			52 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			53 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			55 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			57 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			59 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			61 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			62 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			63 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			64 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			65 : ( CustomizedName("A - Parking Positions | A #"),customOffset_vienna),
			91 : ( CustomizedName("A - Parking Positions CARGO | A #"),customOffset_vienna),
			92 : ( CustomizedName("A - Parking Positions CARGO | A #"),customOffset_vienna),
			93 : ( CustomizedName("A - Parking Positions CARGO | A #"),customOffset_vienna),
			94 : ( CustomizedName("A - Parking Positions CARGO | A #"),customOffset_vienna),
			95 : ( CustomizedName("A - Parking Positions CARGO | A #"),customOffset_vienna),
			96 : ( CustomizedName("A - Parking Positions CARGO | A #"),customOffset_vienna),
			},
	GATE_C : {
		None : (),
			31 : ( CustomizedName("C - Parking Positions | C #"),customOffset_vienna),
			32 : ( CustomizedName("C - Parking Positions | C #"),customOffset_vienna),
			33 : ( CustomizedName("C - Parking Positions | C #"),customOffset_vienna),
			34 : ( CustomizedName("C - Parking Positions | C #"),customOffset_vienna),
			35 : ( CustomizedName("C - Parking Positions | C #"),customOffset_vienna),
			36 : ( CustomizedName("C - Parking Positions | C #"),customOffset_vienna),
			37 : ( CustomizedName("C - Parking Positions | C #"),customOffset_vienna),
			38 : ( CustomizedName("C - Parking Positions | C #"),customOffset_vienna),
			39 : ( CustomizedName("C - Parking Positions | C #"),customOffset_vienna),
			40 : ( CustomizedName("C - Parking Positions | C #"),customOffset_vienna),
			41 : ( CustomizedName("C - Parking Positions | C #"),customOffset_vienna),
			42 : ( CustomizedName("C - Parking Positions | C #"),customOffset_vienna),
			},
	GATE_D : {
		None : (),
			21 : ( CustomizedName("D - Parking Positions | D #"),customOffset_vienna),
			22 : ( CustomizedName("D - Parking Positions | D #"),customOffset_vienna),
			23 : ( CustomizedName("D - Parking Positions | D #"),customOffset_vienna),
			24 : ( CustomizedName("D - Parking Positions | D #"),customOffset_vienna),
			26 : ( CustomizedName("D - Parking Positions | D #"),customOffset_vienna),
			28 : ( CustomizedName("D - Parking Positions | D #"),customOffset_vienna),
			29 : ( CustomizedName("D - Parking Positions | D #"),customOffset_vienna),
			},
	GATE_F : {
		None : (),
			1 : ( CustomizedName("F - Parking Positions ODD | F #"),customOffset_vienna),
			3 : ( CustomizedName("F - Parking Positions ODD | F #"),customOffset_vienna),
			5 : ( CustomizedName("F - Parking Positions ODD | F #"),customOffset_vienna),
			9 : ( CustomizedName("F - Parking Positions ODD | F #"),customOffset_vienna),
			11 : ( CustomizedName("F - Parking Positions ODD | F #"),customOffset_vienna),			
			13 : ( CustomizedName("F - Parking Positions ODD | F #"),customOffset_vienna),			
			17 : ( CustomizedName("F - Parking Positions ODD | F #"),customOffset_vienna),
			21 : ( CustomizedName("F - Parking Positions ODD | F #"),customOffset_vienna),
			23 : ( CustomizedName("F - Parking Positions ODD | F #"),customOffset_vienna),
			27 : ( CustomizedName("F - Parking Positions ODD | F #"),customOffset_vienna),
			31 : ( CustomizedName("F - Parking Positions ODD | F #"),customOffset_vienna),
			35 : ( CustomizedName("F - Parking Positions ODD | F 33/F35"),customOffset_vienna),
			37 : ( CustomizedName("F - Parking Positions ODD | F #"),customOffset_vienna),
			4 : ( CustomizedName("F - Parking Positions EVEN | F #"),customOffset_vienna),
			8 : ( CustomizedName("F - Parking Positions EVEN | F #"),customOffset_vienna),
			12 : ( CustomizedName("F - Parking Positions EVEN | F #"),customOffset_vienna),
			16 : ( CustomizedName("F - Parking Positions EVEN | F #"),customOffset_vienna),
			22 : ( CustomizedName("F - Parking Positions EVEN | F #"),customOffset_vienna),			
			26 : ( CustomizedName("F - Parking Positions EVEN | F 26 / G26"),customOffset_vienna),
			32 : ( CustomizedName("F - Parking Positions EVEN | F #"),customOffset_vienna),
			36 : ( CustomizedName("F - Parking Positions EVEN | F 36 / G36"),customOffset_vienna),
			41 : ( CustomizedName("F - Parking Positions ODD | F #"),customOffset_vienna),
			42 : ( CustomizedName("F - Parking Positions EVEN | F #"),customOffset_vienna),
			43 : ( CustomizedName("F - Parking Positions ODD | F #"),customOffset_vienna),
			44 : ( CustomizedName("F - Parking Positions EVEN | F #"),customOffset_vienna),
			45 : ( CustomizedName("F - Parking Positions ODD | F #"),customOffset_vienna),
			46 : ( CustomizedName("F - Parking Positions EVEN | F #"),customOffset_vienna),
			47 : ( CustomizedName("F - Parking Positions ODD | F #"),customOffset_vienna),
			48 : ( CustomizedName("F - Parking Positions EVEN | F #"),customOffset_vienna),
			49 : ( CustomizedName("F - Parking Positions ODD | F #"),customOffset_vienna),
			50 : ( CustomizedName("F - Parking Positions EVEN | F #"),customOffset_vienna),
			51 : ( CustomizedName("F - Parking Positions ODD | F #"),customOffset_vienna),
			53 : ( CustomizedName("F - Parking Positions ODD | F #"),customOffset_vienna),
			55 : ( CustomizedName("F - Parking Positions ODD | F #"),customOffset_vienna),
			57 : ( CustomizedName("F - Parking Positions ODD | F #"),customOffset_vienna),
			59 : ( CustomizedName("F - Parking Positions ODD | F #"),customOffset_vienna),
			},
	GATE_H : {
		None : (),
			41 : ( CustomizedName("H - Parking Positions | H #"),customOffset_vienna),
			42 : ( CustomizedName("H - Parking Positions | H #"),customOffset_vienna),
			43 : ( CustomizedName("H - Parking Positions | H #"),customOffset_vienna),
			44 : ( CustomizedName("H - Parking Positions | H #"),customOffset_vienna),
			45 : ( CustomizedName("H - Parking Positions | H #"),customOffset_vienna),
			46 : ( CustomizedName("H - Parking Positions | H #"),customOffset_vienna),
			48 : ( CustomizedName("H - Parking Positions | H #"),customOffset_vienna),
			49 : ( CustomizedName("H - Parking Positions | H #"),customOffset_vienna),
			97 : ( CustomizedName("H - Parking Positions | H #"),customOffset_vienna),
			98 : ( CustomizedName("H - Parking Positions | H #"),customOffset_vienna),
			},
	GATE_B : {
		None : (),
			43 : ( CustomizedName("B - Parking Positions CARGO | B # Cargo"),customOffset_vienna),
			47 : ( CustomizedName("B - Parking Positions CARGO | B # Cargo"),customOffset_vienna),
			48 : ( CustomizedName("B - Parking Positions CARGO | B # Cargo"),customOffset_vienna),
			49 : ( CustomizedName("B - Parking Positions CARGO | B # Cargo"),customOffset_vienna),
			51 : ( CustomizedName("B - Parking Positions CARGO | B # Cargo"),customOffset_vienna),
			52 : ( CustomizedName("B - Parking Positions CARGO | B # Cargo"),customOffset_vienna),
			53 : ( CustomizedName("B - Parking Positions CARGO | B # Cargo"),customOffset_vienna),
			57 : ( CustomizedName("B - Parking Positions CARGO | B # Cargo"),customOffset_vienna),
			58 : ( CustomizedName("B - Parking Positions CARGO | B # Cargo"),customOffset_vienna),
			59 : ( CustomizedName("B - Parking Positions CARGO | B # Cargo"),customOffset_vienna),
			61 : ( CustomizedName("B - Parking Positions CARGO | B # Cargo"),customOffset_vienna),
			62 : ( CustomizedName("B - Parking Positions CARGO | B # Cargo"),customOffset_vienna),
			63 : ( CustomizedName("B - Parking Positions CARGO | B # Cargo"),customOffset_vienna),
			67 : ( CustomizedName("B - Parking Positions CARGO | B # Cargo"),customOffset_vienna),
			68 : ( CustomizedName("B - Parking Positions CARGO | B # Cargo"),customOffset_vienna),
			69 : ( CustomizedName("B - Parking Positions CARGO | B # Cargo"),customOffset_vienna),
			71 : ( CustomizedName("B - Parking Positions | B #"),customOffset_vienna),
			72 : ( CustomizedName("B - Parking Positions | B #"),customOffset_vienna),
			73 : ( CustomizedName("B - Parking Positions | B #"),customOffset_vienna),
			74 : ( CustomizedName("B - Parking Positions | B #"),customOffset_vienna),
			75 : ( CustomizedName("B - Parking Positions | B #"),customOffset_vienna),
			81 : ( CustomizedName("B - Parking Positions | B #"),customOffset_vienna),
			82 : ( CustomizedName("B - Parking Positions | B #"),customOffset_vienna),
			83 : ( CustomizedName("B - Parking Positions | B #"),customOffset_vienna),
			84 : ( CustomizedName("B - Parking Positions | B #"),customOffset_vienna),
			85 : ( CustomizedName("B - Parking Positions | B #"),customOffset_vienna),
			91 : ( CustomizedName("B - Parking Positions | B #"),customOffset_vienna),
			92 : ( CustomizedName("B - Parking Positions | B #"),customOffset_vienna),
			93 : ( CustomizedName("B - Parking Positions | B #"),customOffset_vienna),
			94 : ( CustomizedName("B - Parking Positions | B #"),customOffset_vienna),
			95 : ( CustomizedName("B - Parking Positions | B #"),customOffset_vienna),
			96 : ( CustomizedName("B - Parking Positions | B #"),customOffset_vienna),
			},
	GATE_E : {
		None : (),
			41 : ( CustomizedName("E - Parking Positions | E #"),customOffset_vienna),
			42 : ( CustomizedName("E - Parking Positions | E #"),customOffset_vienna),
			43 : ( CustomizedName("E - Parking Positions | E #"),customOffset_vienna),
			44 : ( CustomizedName("E - Parking Positions | E #"),customOffset_vienna),
			45 : ( CustomizedName("E - Parking Positions | E #"),customOffset_vienna),
			46 : ( CustomizedName("E - Parking Positions | E #"),customOffset_vienna),
			47 : ( CustomizedName("E - Parking Positions | E #"),customOffset_vienna),
			48 : ( CustomizedName("E - Parking Positions | E #"),customOffset_vienna),
			49 : ( CustomizedName("E - Parking Positions | E #"),customOffset_vienna),
			50 : ( CustomizedName("E - Parking Positions | E #"),customOffset_vienna),
			51 : ( CustomizedName("E - Parking Positions | E #"),customOffset_vienna),
			52 : ( CustomizedName("E - Parking Positions | E #"),customOffset_vienna),
			},
	GATE_K : {
		None : (),
			41 : ( CustomizedName("K - Parking Positions | K #"),customOffset_vienna),
			42 : ( CustomizedName("K - Parking Positions | K #"),customOffset_vienna),
			43 : ( CustomizedName("K - Parking Positions | K #"),customOffset_vienna),
			44 : ( CustomizedName("K - Parking Positions | K #"),customOffset_vienna),
			45 : ( CustomizedName("K - Parking Positions | K #"),customOffset_vienna),
			46 : ( CustomizedName("K - Parking Positions | K #"),customOffset_vienna),
			47 : ( CustomizedName("K - Parking Positions | K #"),customOffset_vienna),
			48 : ( CustomizedName("K - Parking Positions | K #"),customOffset_vienna),
			49 : ( CustomizedName("K - Parking Positions | K #"),customOffset_vienna),
			50 : ( CustomizedName("K - Parking Positions | K #"),customOffset_vienna),
			51 : ( CustomizedName("K - Parking Positions | K #"),customOffset_vienna),
			}
}




